site_name: MongooseIM
docs_dir: doc
theme: readthedocs
site_favicon: favicon.ico
extra_templates: []
extra_css: ["custom.css"]
extra_javascript: []

pages:
  - Home: 'index.md'
  - User Guide:
      - 'Features and supported standards': 'user-guide/Features-and-supported-standards.md'
      - 'Get to know MongooseIM': 'user-guide/Get-to-know-MongooseIM.md'
      - 'Getting started': 'user-guide/Getting-started.md'
      - 'Release/Installation configuration': 'user-guide/release_config.md'
      - 'High-level Architecture': 'user-guide/MongooseIM-High-level-Architecture.md'
  - How to:
      - 'Build MongooseIM from source code': 'user-guide/How-to-build.md'
      - 'Set up MongoosePush': 'user-guide/Push-notifications.md'
      - 'Set up MongooseICE': 'user-guide/ICE_tutorial.md'
      - 'Build an iOS messaging app': 'user-guide/iOS_tutorial.md'
  - Platform:
      - 'Roadmap': 'Roadmap.md'
      - 'Contributions to ecosystem': 'Contributions.md'
      - 'Differentiators': 'Differentiators.md'
      - 'History': 'History.md'
  - 'Basic Configuration': 'Basic-configuration.md'
  - 'Advanced Configuration':
      - 'Top-level options': 'Advanced-configuration.md'
      - 'Database backends configuration': 'advanced-configuration/database-backends-configuration.md'
      - 'Listener Modules': 'advanced-configuration/Listener-modules.md'
      - 'Extension Modules': 'advanced-configuration/Modules.md'
      - 'ACL': 'advanced-configuration/acl.md'
  - 'Authentication backends':
      - 'External Authentication Module': 'authentication-backends/External-authentication-module.md'
      - 'HTTP Authentication Module': 'authentication-backends/HTTP-authentication-module.md'
      - 'JWT Authentication Module': 'authentication-backends/JWT-authentication-module.md'
      - 'LDAP Authentication Module': 'authentication-backends/LDAP-authentication-module.md'
  - 'MongooseIM open XMPP extensions':
      - 'MUC light': 'open-extensions/muc_light.md'
      - 'Token-based reconnection': 'open-extensions/token-reconnection.md'
  - 'REST API':
      - 'Client/frontend': 'rest-api/Client-frontend.md'
      - 'Metrics backend': 'rest-api/Metrics-backend.md'
      - 'Administration backend': 'rest-api/Administration-backend.md'
  - 'Modules':
      - 'mod_adhoc': 'modules/mod_adhoc.md'
      - 'mod_admin_extra': 'modules/mod_admin_extra.md'
      - 'mod_amp': 'modules/mod_amp.md'
      - 'mod_auth_token': 'modules/mod_auth_token.md'
      - 'mod_aws_sns': 'modules/mod_aws_sns.md'
      - 'mod_auth_token': 'modules/mod_auth_token.md'
      - 'mod_blocking': 'modules/mod_blocking.md'
      - 'mod_bosh': 'modules/mod_bosh.md'
      - 'mod_caps': 'modules/mod_caps.md'
      - 'mod_carboncopy': 'modules/mod_carboncopy.md'
      - 'mod_commands': 'modules/mod_commands.md'
      - 'mod_csi': 'modules/mod_csi.md'
      - 'mod_disco': 'modules/mod_disco.md'
      - 'mod_http_notification': 'modules/mod_http_notification.md'
      - 'mod_http_upload': 'modules/mod_http_upload.md'
      - 'mod_keystore': 'modules/mod_keystore.md'
      - 'mod_last': 'modules/mod_last.md'
      - 'mod_mam': 'modules/mod_mam.md'
      - 'mod_muc': 'modules/mod_muc.md'
      - 'mod_muc_commands': 'modules/mod_muc_commands.md'
      - 'mod_muc_log': 'modules/mod_muc_log.md'
      - 'mod_muc_light': 'modules/mod_muc_light.md'
      - 'mod_muc_light_commands': 'modules/mod_muc_light_commands.md'
      - 'mod_offline': 'modules/mod_offline.md'
      - 'mod_offline_stub': 'modules/mod_offline_stub.md'
      - 'mod_ping': 'modules/mod_ping.md'
      - 'mod_privacy': 'modules/mod_privacy.md'
      - 'mod_private': 'modules/mod_private.md'
      - 'mod_pubsub': 'modules/mod_pubsub.md'
      - 'mod_push': 'modules/mod_push.md'
      - 'mod_push_service_mongoosepush': 'modules/mod_push_service_mongoosepush.md'
      - 'mod_register': 'modules/mod_register.md'
      - 'mod_revproxy': 'modules/mod_revproxy.md'
      - 'mod_roster': 'modules/mod_roster.md'
      - 'mod_shared_roster_ldap': 'modules/mod_shared_roster_ldap.md'
      - 'mod_sic': 'modules/mod_sic.md'
      - 'mod_stream_management': 'modules/mod_stream_management.md'
      - 'mod_time': 'modules/mod_time.md'
      - 'mod_vcard': 'modules/mod_vcard.md'
      - 'mod_version': 'modules/mod_version.md'
  - 'Operation and maintenance':
      - 'Cluster management considerations': 'operation-and-maintenance/Cluster-management-considerations.md'
      - 'Cluster configuration and node management': 'operation-and-maintenance/Cluster-configuration-and-node-management.md'
      - 'Logging & monitoring': 'operation-and-maintenance/Logging-&-monitoring.md'
      - 'Reloading configuration on a running system': 'operation-and-maintenance/Reloading-configuration-on-a-running-system.md'
      - 'Metrics': 'operation-and-maintenance/Mongoose-metrics.md'
      - 'Distribution over TLS': 'operation-and-maintenance/tls-distribution.md'
  - "Developer's guide":
      - 'Testing MongooseIM': 'developers-guide/Testing-MongooseIM.md'
      - 'Hooks and Handlers': 'developers-guide/Hooks-and-handlers.md'
      - 'Hooks description': 'developers-guide/hooks_description.md'
      - 'Stanza routing': 'developers-guide/message_routing.md'
      - 'Accumulators':  'developers-guide/accumulators.md'
      - 'mod_amp development': 'developers-guide/mod_amp_developers_guide.md'
      - 'mod_muc_light developers doc': 'developers-guide/mod_muc_light_developers_guide.md'
      - 'SCRAM serialization format': 'developers-guide/SCRAM-serialization.md'
      - 'xep-tool usage': 'developers-guide/xep_tool.md'
      - 'FIPS mode': 'developers-guide/OpenSSL-and-FIPS.md'
