site_name: MongooseIM
docs_dir: doc
theme: readthedocs
site_favicon: favicon.ico
extra_templates: []

pages:
  - Home: 'index.md'
  - User Guide:
      - 'Features and supported standards': 'user-guide/Features-and-supported-standards.md'
      - 'Get to know MongooseIM': 'user-guide/Get-to-know-MongooseIM.md'
      - 'Getting started': 'user-guide/Getting-started.md'
      - 'Release/Installation configuration': 'user-guide/release_config.md'
      - 'High-level Architecture': 'user-guide/MongooseIM-High-level-Architecture.md'
  - 'Basic Configuration Overview': 'Basic-configuration.md'
  - 'Advanced Configuration Overview': 'Advanced-configuration.md'
  - 'Advanced Configuration':
      - 'Database backends configuration': 'advanced-configuration/database-backends-configuration.md'
      - 'Cassandra configuration': 'advanced-configuration/Cassandra.md'
      - 'HTTP Authentication Module': 'advanced-configuration/HTTP-authentication-module.md'
      - 'Listener Modules': 'advanced-configuration/Listener-modules.md'
      - 'Extension Modules': 'advanced-configuration/Modules.md'
      - 'ACL': 'advanced-configuration/acl.md'
  - 'MongooseIM open XMPP extensions':
      - 'MUC light': 'open-extensions/muc_light.md'
      - 'Token-based reconnection': 'open-extensions/token-reconnection.md'
  - 'Modules':
      - 'mod_adhoc': 'modules/mod_adhoc.md'
      - 'mod_admin_extra': 'modules/mod_admin_extra.md'
      - 'mod_amp': 'modules/mod_amp.md'
      - 'mod_auth_token': 'modules/mod_auth_token.md'
      - 'mod_blocking': 'modules/mod_blocking.md'
      - 'mod_bosh': 'modules/mod_bosh.md'
      - 'mod_carboncopy': 'modules/mod_carboncopy.md'
      - 'mod_csi': 'modules/mod_csi.md'
      - 'mod_disco': 'modules/mod_disco.md'
      - 'mod_http_notification': 'modules/mod_http_notification.md'
      - 'mod_keystore': 'modules/mod_keystore.md'
      - 'mod_last': 'modules/mod_last.md'
      - 'mod_mam': 'modules/mod_mam.md'
      - 'mod_muc': 'modules/mod_muc.md'
      - 'mod_muc_log': 'modules/mod_muc_log.md'
      - 'mod_muc_light': 'modules/mod_muc_light.md'
      - 'mod_offline': 'modules/mod_offline.md'
      - 'mod_ping': 'modules/mod_ping.md'
      - 'mod_privacy': 'modules/mod_privacy.md'
      - 'mod_private': 'modules/mod_private.md'
      - 'mod_pubsub': 'modules/mod_pubsub.md'
      - 'mod_register': 'modules/mod_register.md'
      - 'mod_revproxy': 'modules/mod_revproxy.md'
      - 'mod_roster': 'modules/mod_roster.md'
      - 'mod_shared_roster_ldap': 'modules/mod_shared_roster_ldap.md'
      - 'mod_sic': 'modules/mod_sic.md'
      - 'mod_stream_management': 'modules/mod_stream_management.md'
      - 'mod_time': 'modules/mod_time.md'
      - 'mod_vcard': 'modules/mod_vcard.md'
      - 'mod_version': 'modules/mod_version.md'
      - 'mod_websockets': 'modules/mod_websockets.md'
  - 'Operation and maintenance':
      - 'Cluster configuration and node management': 'operation-and-maintenance/Cluster-configuration-and-node-management.md'
      - 'Logging & monitoring': 'operation-and-maintenance/Logging-&-monitoring.md'
      - 'Reloading configuration on a running system': 'operation-and-maintenance/Reloading-configuration-on-a-running-system.md'
      - 'Metrics': 'operation-and-maintenance/Mongoose-metrics.md'
      - 'HTTP Administration API': 'http-administration-api-documentation.md'
  - "Developer's guide":
      - 'Testing MongooseIM': 'developers-guide/Testing-MongooseIM.md'
      - 'REST interface to metrics': 'developers-guide/REST-interface-to-metrics.md'
      - 'Hooks and Handlers': 'developers-guide/Hooks-and-handlers.md'
      - 'Hooks description': 'developers-guide/hooks_description.md'
      - 'Stanza routing': 'developers-guide/message_routing.md'
      - 'mod_amp development': 'developers-guide/mod_amp_developers_guide.md'
      - 'mod_muc_light developers doc': 'developers-guide/mod_muc_light_developers_guide.md'
      - 'xep-tool usage': 'developers-guide/xep_tool.md'
      - 'FIPS mode': 'developers-guide/OpenSSL-and-FIPS.md'
