site_name: MongooseIM
site_description: "MongooseIM is a mobile messaging platform with focus on performance and scalability"
site_author: "Erlang Solutions"
site_url: https://esl.github.io/MongooseDocs/latest/
repo_url: https://github.com/esl/MongooseIM
edit_uri: edit/master/doc/
docs_dir: doc
theme:
  name: material
  favicon: favicon.ico
  logo: MongooseIM_logo_white.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/mongooseim/mongooseim/
    - icon: fontawesome/brands/github
      link: https://github.com/esl/MongooseIM
plugins:
  - include-markdown
  - search:
      lang: en
extra_css: [css/custom.css]
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 'Home': 'index.md'
  - 'Getting Started':
      - 'Installation': 'getting-started/Installation.md'
      - 'Quick Setup': 'getting-started/Quick-setup.md'
  - 'User Guide':
      - 'Features': 'user-guide/Features.md'
      - 'Supported Standards': 'user-guide/Supported-standards.md'
      - 'High-level Architecture': 'user-guide/High-level-Architecture.md'
  - Tutorials:
      - 'How to Build MongooseIM from source code': 'tutorials/How-to-build.md'
      - 'How to build and run MongooseIM docker image': 'tutorials/Docker-build.md'
      - 'How to configure MongooseIM to use CETS instead of Mnesia': 'tutorials/CETS-configure.md'
      - 'How to Set up Push Notifications': 'tutorials/push-notifications/Push-notifications.md'
      - 'How to Set up Push Notifications on the client side': 'tutorials/push-notifications/Push-notifications-client-side.md'
      - 'How to Set up MongoosePush': 'tutorials/push-notifications/MongoosePush-setup.md'
      - 'How to Set up MongooseICE': 'tutorials/ICE_tutorial.md'
      - 'How to Build an iOS messaging app': 'tutorials/iOS_tutorial.md'
      - 'How to Set up Jingle/SIP': 'tutorials/Jingle-SIP-setup.md'
      - 'How to Set up SASL client certificate authentication': 'tutorials/client-certificate.md'
  - 'Open XMPP Extensions':
      - 'MUC light': 'open-extensions/muc_light.md'
      - 'Inbox': 'open-extensions/inbox.md'
      - 'Smart Markers': 'open-extensions/smart-markers.md'
      - 'Token-based reconnection': 'open-extensions/token-reconnection.md'
      - 'MAM': 'open-extensions/mam.md'
  - Configuration:
      - 'Configuration Files': 'configuration/configuration-files.md'
      - 'Options: General': 'configuration/general.md'
      - 'Options: Listen': 'configuration/listen.md'
      - 'Options: Auth': 'configuration/auth.md'
      - 'Options: Internal Databases': 'configuration/internal-databases.md'
      - 'Options: Outgoing connections': 'configuration/outgoing-connections.md'
      - 'Options: Services': 'configuration/Services.md'
      - 'Options: Extension Modules': 'configuration/Modules.md'
      - 'Options: Shaper': 'configuration/shaper.md'
      - 'Options: Acl': 'configuration/acl.md'
      - 'Options: Access': 'configuration/access.md'
      - 'Options: S2S': 'configuration/s2s.md'
      - 'Options: Host config': 'configuration/host_config.md'
      - 'Release Options': 'configuration/release-options.md'
      - 'Erlang Cookie Security': 'configuration/Erlang-cookie-security.md'
      - 'TLS Hardening': 'configuration/TLS-hardening.md'
      - 'Database Backends Configuration': 'configuration/database-backends-configuration.md'
  - 'Authentication Methods':
      - 'RDBMS': 'authentication-methods/rdbms.md'
      - 'External': 'authentication-methods/external.md'
      - 'Anonymous': 'authentication-methods/anonymous.md'
      - 'LDAP': 'authentication-methods/ldap.md'
      - 'JWT': 'authentication-methods/jwt.md'
      - 'HTTP': 'authentication-methods/http.md'
      - 'PKI': 'authentication-methods/pki.md'
      - 'Dummy': 'authentication-methods/dummy.md'
  - 'Extension modules':
      - 'mod_adhoc': 'modules/mod_adhoc.md'
      - 'mod_amp': 'modules/mod_amp.md'
      - 'mod_auth_token': 'modules/mod_auth_token.md'
      - 'mod_bind2': 'modules/mod_bind2.md'
      - 'mod_blocking': 'modules/mod_blocking.md'
      - 'mod_bosh': 'modules/mod_bosh.md'
      - 'mod_caps': 'modules/mod_caps.md'
      - 'mod_cache_users': 'modules/mod_cache_users.md'
      - 'mod_carboncopy': 'modules/mod_carboncopy.md'
      - 'mod_csi': 'modules/mod_csi.md'
      - 'mod_disco': 'modules/mod_disco.md'
      - 'mod_domain_isolation': 'modules/mod_domain_isolation.md'
      - 'mod_event_pusher':
          - 'mod_event_pusher': 'modules/mod_event_pusher.md'
          - 'HTTP backend': 'modules/mod_event_pusher_http.md'
          - 'Push backend': 'modules/mod_event_pusher_push.md'
          - 'RabbitMQ backend': 'modules/mod_event_pusher_rabbit.md'
          - 'SNS backend': 'modules/mod_event_pusher_sns.md'
      - 'mod_extdisco': 'modules/mod_extdisco.md'
      - 'mod_global_distrib': 'modules/mod_global_distrib.md'
      - 'mod_http_upload': 'modules/mod_http_upload.md'
      - 'mod_inbox': 'modules/mod_inbox.md'
      - 'mod_jingle_sip': 'modules/mod_jingle_sip.md'
      - 'mod_keystore': 'modules/mod_keystore.md'
      - 'mod_last': 'modules/mod_last.md'
      - 'mod_mam': 'modules/mod_mam.md'
      - 'mod_muc': 'modules/mod_muc.md'
      - 'mod_muc_log': 'modules/mod_muc_log.md'
      - 'mod_muc_light': 'modules/mod_muc_light.md'
      - 'mod_offline': 'modules/mod_offline.md'
      - 'mod_offline_stub': 'modules/mod_offline_stub.md'
      - 'mod_ping': 'modules/mod_ping.md'
      - 'mod_presence': 'modules/mod_presence.md'
      - 'mod_privacy': 'modules/mod_privacy.md'
      - 'mod_private': 'modules/mod_private.md'
      - 'mod_pubsub': 'modules/mod_pubsub.md'
      - 'mod_push_service_mongoosepush': 'modules/mod_push_service_mongoosepush.md'
      - 'mod_register': 'modules/mod_register.md'
      - 'mod_roster': 'modules/mod_roster.md'
      - 'mod_sasl2': 'modules/mod_sasl2.md'
      - 'mod_shared_roster_ldap': 'modules/mod_shared_roster_ldap.md'
      - 'mod_smart_markers': 'modules/mod_smart_markers.md'
      - 'mod_sic': 'modules/mod_sic.md'
      - 'mod_stream_management': 'modules/mod_stream_management.md'
      - 'mod_time': 'modules/mod_time.md'
      - 'mod_vcard': 'modules/mod_vcard.md'
      - 'mod_version': 'modules/mod_version.md'
  - 'REST API':
      - 'Client/frontend': 'rest-api/Client-frontend.md'
      - 'Administration backend': 'rest-api/Administration-backend.md'
  - 'GraphQL API':
      - 'User': 'graphql-api/User-GraphQL.md'
      - 'Admin': 'graphql-api/Admin-GraphQL.md'
  - 'Operation and Maintenance':
      - 'GDPR considerations': 'operation-and-maintenance/gdpr-considerations.md'
      - 'Cluster management considerations': 'operation-and-maintenance/Cluster-management-considerations.md'
      - 'Cluster configuration and node management': 'operation-and-maintenance/Cluster-configuration-and-node-management.md'
      - 'Logging & monitoring': 'operation-and-maintenance/Logging-&-monitoring.md'
      - 'Logging configuration': 'operation-and-maintenance/Logging.md'
      - 'Logging with Humio': 'operation-and-maintenance/Humio.md'
      - 'Logging fields': 'operation-and-maintenance/Logging-fields.md'
      - 'Rolling upgrade': 'operation-and-maintenance/Rolling-upgrade.md'
      - 'Cluster restart': 'operation-and-maintenance/Cluster-restart.md'
      - 'Metrics': 'operation-and-maintenance/MongooseIM-metrics.md'
      - 'System Metrics Privacy Policy': 'operation-and-maintenance/System-Metrics-Privacy-Policy.md'
      - 'Distribution over TLS': 'operation-and-maintenance/tls-distribution.md'
      - 'Known issues': 'operation-and-maintenance/known-issues.md'
  - "Developer's Guide":
      - 'Release/Installation configuration': 'developers-guide/release_config.md'
      - 'Bootstrap scripts': 'developers-guide/Bootstrap-Scripts.md'
      - 'Testing MongooseIM': 'developers-guide/Testing-MongooseIM.md'
      - 'Logging': 'developers-guide/logging.md'
      - 'Hooks and Handlers': 'developers-guide/Hooks-and-handlers.md'
      - 'Hooks description': 'developers-guide/hooks_description.md'
      - 'Accumulators':  'developers-guide/accumulators.md'
      - 'Stanza routing': 'developers-guide/Stanza-routing.md'
      - 'Domain management': 'developers-guide/domain_management.md'
      - 'mod_amp development': 'developers-guide/mod_amp_developers_guide.md'
      - 'mod_muc_light developers doc': 'developers-guide/mod_muc_light_developers_guide.md'
      - 'SCRAM serialization format': 'developers-guide/SCRAM-serialization.md'
      - 'xep-tool usage': 'developers-guide/xep_tool.md'
      - 'FIPS mode': 'developers-guide/OpenSSL-and-FIPS.md'
      - 'Basic IQ Handler': 'developers-guide/Basic-iq-handler.md'
      - 'mongoose_wpool': 'developers-guide/mongoose_wpool.md'
  - Migration Guide:
      - '3.1.1 to 3.2.0': 'migrations/3.1.1_3.2.0.md'
      - '3.3.0 to 3.4.0': 'migrations/3.3.0_3.4.0.md'
      - '3.5.0 to 3.6.0': 'migrations/3.5.0_3.6.0.md'
      - '3.6.0 to 3.7.0': 'migrations/3.6.0_3.7.0.md'
      - '3.7.0 to 4.0.0': 'migrations/3.7.0_4.0.0.md'
      - '4.0.0 to 4.0.1': 'migrations/4.0.0_4.0.1.md'
      - '4.0.1 to 4.1.0': 'migrations/4.0.1_4.1.0.md'
      - '4.1.0 to 4.2.0': 'migrations/4.1.0_4.2.0.md'
      - '4.2.0 to 5.0.0': 'migrations/4.2.0_5.0.0.md'
      - '5.0.0 to 5.1.0': 'migrations/5.0.0_5.1.0.md'
      - '5.1.0 to 6.0.0': 'migrations/5.1.0_6.0.0.md'
      - '6.0.0 to 6.1.0': 'migrations/6.0.0_6.1.0.md'
      - '6.1.0 to 6.2.0': 'migrations/6.1.0_6.2.0.md'
      - '6.2.0 to 6.2.1': 'migrations/6.2.0_6.2.1.md'
      - 'MAM MUC migration helper': 'migrations/jid-from-mam-muc-script.md'
  - 'Contributions to the Ecosystem': 'Contributions.md'
  - 'MongooseIM History': 'History.md'
