[general]
  loglevel = "warning"
  hosts = [{{{hosts}}}]
  registration_timeout = "infinity"
  language = "en"
  all_metrics_are_global = {{{all_metrics_are_global}}}
  sm_backend = {{{sm_backend}}}
  max_fsm_queue = 1000
  {{{http_server_name}}}
  {{{rdbms_server_type}}}

[[listen.http]]
  port = {{{http_port}}}
  transport.num_acceptors = 10
  transport.max_connections = 1024

  [[listen.http.handlers.mod_bosh]]
    host = "_"
    path = "/http-bind"

  [[listen.http.handlers.mod_websockets]]
    host = "_"
    path = "/ws-xmpp"

    [listen.http.handlers.mod_websockets.service]
      access = "all"
      shaper_rule = "fast"
      password = "secret"

[[listen.http]]
  port = {{{https_port}}}
  transport.num_acceptors = 10
  transport.max_connections = 1024
  {{{https_config}}}

  [[listen.http.handlers.mod_bosh]]
    host = "_"
    path = "/http-bind"

  [[listen.http.handlers.mod_websockets]]
    host = "_"
    path = "/ws-xmpp"

[[listen.http]]
  {{{http_api_endpoint}}}
  transport.num_acceptors = 10
  transport.max_connections = 1024

  [[listen.http.handlers.mongoose_api_admin]]
    host = "localhost"
    path = "/api"

[[listen.http]]
  {{{http_api_client_endpoint}}}
  transport.num_acceptors = 10
  transport.max_connections = 1024
  protocol.compress = true
  {{{https_config}}}

  [[listen.http.handlers.lasse_handler]]
    host = "_"
    path = "/api/sse"
    module = "mongoose_client_api_sse"

  [[listen.http.handlers.mongoose_client_api_messages]]
    host = "_"
    path = "/api/messages/[:with]"

  [[listen.http.handlers.mongoose_client_api_contacts]]
    host = "_"
    path = "/api/contacts/[:jid]"

  [[listen.http.handlers.mongoose_client_api_rooms]]
    host = "_"
    path = "/api/rooms/[:id]"

  [[listen.http.handlers.mongoose_client_api_rooms_config]]
    host = "_"
    path = "/api/rooms/[:id]/config"

  [[listen.http.handlers.mongoose_client_api_rooms_users]]
    host = "_"
    path = "/api/rooms/:id/users/[:user]"

  [[listen.http.handlers.mongoose_client_api_rooms_messages]]
    host = "_"
    path = "/api/rooms/[:id]/messages"

  [[listen.http.handlers.cowboy_swagger_redirect_handler]]
    host = "_"
    path = "/api-docs"

  [[listen.http.handlers.cowboy_swagger_json_handler]]
    host = "_"
    path = "/api-docs/swagger.json"

  [[listen.http.handlers.cowboy_static]]
    host = "_"
    path = "/api-docs/[...]"
    type = "priv_dir"
    app = "cowboy_swagger"
    content_path = "swagger"

[[listen.http]]
  {{{http_api_old_endpoint}}}
  transport.num_acceptors = 10
  transport.max_connections = 1024

  [[listen.http.handlers.mongoose_api]]
    host = "localhost"
    path = "/api"
    handlers = ["mongoose_api_metrics", "mongoose_api_users"]

[[listen.c2s]]
  port = {{{c2s_port}}}
  {{{tls_config}}}
  {{{tls_module}}}
  {{{proxy_protocol}}}
  {{{zlib}}}
  access = "c2s"
  shaper = "c2s_shaper"
  max_stanza_size = 65536
  {{{c2s_dhfile}}}

{{{secondary_c2s}}}

[[listen.s2s]]
  port = {{{incoming_s2s_port}}}
  shaper = "s2s_shaper"
  max_stanza_size = 131072
  {{{s2s_dhfile}}}

{{{listen_service}}}

[auth]
  {{{auth_ldap}}}
  methods = [{{{auth_method}}}]
  {{{password_format}}}
  {{{scram_iterations}}}
  sasl_external = [{{{cyrsasl_external}}}]
  {{{sasl_mechanisms}}}

{{{outgoing_pools}}}
#[outgoing_pools.redis.global_distrib]
#  scope = "single_host"
#  host = "localhost"
#  workers = 10
#
#[outgoing_pools.rdbms.default]
#  scope = "global"
#  workers = 5
#
#  [outgoing_pools.rdbms.default.connection]
#    driver = "pgsql"
#    host = "localhost"
#    database = "ejabberd"
#    username = "ejabberd"
#    password = "mongooseim_secret"
#    tls.required = true
#    tls.verify_peer = true
#    tls.cacertfile = "priv/ssl/cacert.pem"
#    tls.server_name_indication = false

[services.service_admin_extra]
  submods = ["node", "accounts", "sessions", "vcard", "gdpr", "upload",
             "roster", "last", "private", "stanza", "stats"]

[services.service_mongoose_system_metrics]
  initial_report = 300_000
  periodic_report = 10_800_000

[modules.mod_adhoc]

{{{mod_amp}}}

[modules.mod_disco]
  users_can_see_hidden_services = false

[modules.mod_commands]

[modules.mod_muc_commands]

[modules.mod_muc_light_commands]

{{{mod_last}}}

[modules.mod_stream_management]

{{{mod_offline}}}

{{{mod_privacy}}}

{{{mod_blocking}}}

{{{mod_private}}}

[modules.mod_register]
  welcome_message = {body = "", subject = ""}
  ip_access = [
    {address = "127.0.0.0/8", policy = "allow"},
    {address = "0.0.0.0/0", policy = "deny"}
  ]
  access = "register"

{{{mod_roster}}}

[modules.mod_sic]

{{{mod_vcard}}}

[modules.mod_bosh]

[modules.mod_carboncopy]

[shaper.normal]
  max_rate = 1000

[shaper.fast]
  max_rate = 50_000

[shaper.mam_shaper]
  max_rate = 1

[shaper.mam_global_shaper]
  max_rate = 1000

[acl]
  local = [
    {user_regexp = ""}
  ]

[access]
  max_user_sessions = [
    {acl = "all", value = 10}
  ]

  max_user_offline_messages = [
    {acl = "admin", value = 5000},
    {acl = "all", value = 100}
  ]

  local = [
    {acl = "local", value = "allow"}
  ]

  c2s = [
    {acl = "blocked", value = "deny"},
    {acl = "all", value = "allow"}
  ]

  c2s_shaper = [
    {acl = "admin", value = "none"},
    {acl = "all", value = "normal"}
  ]

  s2s_shaper = [
    {acl = "all", value = "fast"}
  ]

  muc_admin = [
    {acl = "admin", value = "allow"}
  ]

  muc_create = [
    {acl = "local", value = "allow"}
  ]

  muc = [
    {acl = "all", value = "allow"}
  ]

  register = [
    {acl = "all", value = "allow"}
  ]

  mam_set_prefs = [
    {acl = "all", value = "default"}
  ]

  mam_get_prefs = [
    {acl = "all", value = "default"}
  ]

  mam_lookup_messages = [
    {acl = "all", value = "default"}
  ]

  mam_set_prefs_shaper = [
    {acl = "all", value = "mam_shaper"}
  ]

  mam_get_prefs_shaper = [
    {acl = "all", value = "mam_shaper"}
  ]

  mam_lookup_messages_shaper = [
    {acl = "all", value = "mam_shaper"}
  ]

  mam_set_prefs_global_shaper = [
    {acl = "all", value = "mam_global_shaper"}
  ]

  mam_get_prefs_global_shaper = [
    {acl = "all", value = "mam_global_shaper"}
  ]

  mam_lookup_messages_global_shaper = [
    {acl = "all", value = "mam_global_shaper"}
  ]

[s2s]
  {{{s2s_use_starttls}}}
  {{{s2s_certfile}}}
  default_policy = {{{s2s_default_policy}}}
  outgoing.port = {{{outgoing_s2s_port}}}

  {{{s2s_addr}}}

{{{host_config}}}
#[[host_config]]
#  host = "anonymous.localhost"
#
#  [host_config.auth]
#    methods = ["anonymous"]
#    anonymous.allow_multiple_connections = true
#    anonymous.protocol = "both"
